/**
 * pipeline-data.ts — Architecture stage metadata and mathematical specifications for the Spotify ML Pipeline.
 * Fully aligned with madonna-spotipy-als_v3 notebook results.
 */

import type { PipelineStage } from './spotify-types';

export const PIPELINE_STAGES: readonly PipelineStage[] = [
	{
		id: 'stage-1',
		stageNumber: 1,
		title: 'Data Ingestion & Deduplication',
		subtitle: 'Catalog Ingestion & ±2s Duration Hashing (Sec 1–3)',
		stageTag: 'STAGE 01',
		stageType: 'preprocessing',
		themeColor: 'var(--geo-red)',
		categoryBadge: 'DATA PREPARATION',
		objective: 'Filter Madonna catalog via artist ID 6tbjWDEIzxoDsBA1FuhfPW, convert release dates to years, and de-dupe tracks within a ±2s duration window to eliminate reissue/remaster artifacts.',
		formulaBadge: 'Bucket(t) = round(duration_ms / 2000) ∧ drop_duplicates([name, Bucket])',
		latexFormula: '\\text{Bucket}(t) = \\left\\lfloor \\frac{\\text{duration\\_ms}}{2000} + 0.5 \\right\\rfloor \\quad\\land\\quad \\text{DropDuplicates}(\\text{name}, \\text{Bucket})',
		metricBadge: '169 CANONICAL TRACKS (1983–2015)',
		keyStatLabel: 'Deduplicated Corpus',
		keyStatValue: '169 Clean Masters',
		techSummary: 'Raw Kaggle dataset (spotify-dataset-19212020-600k-tracks) contains multiple entries for remasters and anniversary reissues that artificially inflate cluster sizes. Exact title matching + 2-second duration rounding strips duplicate recordings without losing unique tracks.',
		bullets: [
			'Filtered artists.csv and tracks.csv by exact Madonna ID: 6tbjWDEIzxoDsBA1FuhfPW.',
			'Duration bucketing (±2000ms window) eliminates redundant album reissues.',
			'Sorted by popularity before deduplication to retain the canonical highest-quality master.',
		],
		graphicType: 'dedup',
	},
	{
		id: 'stage-2',
		stageNumber: 2,
		title: 'Feature Correlation & Power Scaling',
		subtitle: '9 Audio Features & Yeo-Johnson Variance Normalization (Sec 4–5)',
		stageTag: 'STAGE 02',
		stageType: 'transformation',
		themeColor: 'var(--geo-blue)',
		categoryBadge: 'FEATURE ENGINEERING',
		objective: 'Examine Pearson correlation across 9 audio features (retaining energy and loudness) and apply PowerTransformer (Yeo-Johnson) to stabilize heavy right-skewed distributions.',
		formulaBadge: 'ψ(λ, y) = ((y + 1)^λ - 1) / λ   (for λ ≠ 0, y ≥ 0)',
		latexFormula: '\\psi(\\lambda, y) = \\begin{cases} \\dfrac{(y + 1)^\\lambda - 1}{\\lambda} & \\text{if } \\lambda \\neq 0, \\, y \\ge 0 \\\\[6pt] \\ln(y + 1) & \\text{if } \\lambda = 0, \\, y \\ge 0 \\end{cases}',
		metricBadge: '9 CONTINUOUS AUDIO FEATURES',
		keyStatLabel: 'Distribution Shape',
		keyStatValue: 'Yeo-Johnson Gaussian Reshape',
		techSummary: 'Features like instrumentalness, speechiness, and liveness are heavily right-skewed with extreme tails. RobustScaler only shifts scale without altering shape, leaving outliers in solitary clusters. Yeo-Johnson reshapes distributions into standard normal curves (μ=0, σ=1). Energy and loudness (r ≈ 0.6–0.8) are both preserved for production vs intensity.',
		bullets: [
			'Full 9 features: danceability, energy, loudness, speechiness, acousticness, instrumentalness, liveness, valence, tempo.',
			'Energy & loudness retained to capture distinct dimensions: production era vs perceived acoustic intensity.',
			'PowerTransformer (Yeo-Johnson) prevents solitary outlier clustering by reshaping tails.',
		],
		graphicType: 'power-transform',
		imageSrc: '/assets/spotify/eda_features.png',
	},
	{
		id: 'stage-3',
		stageNumber: 3,
		title: 'K-Selection Diagnostics & Stability Sweep',
		subtitle: 'Elbow, Silhouette, BIC/AIC & 15-Seed Stability Range (Sec 6 & 6b)',
		stageTag: 'STAGE 03',
		stageType: 'clustering',
		themeColor: 'var(--geo-yellow)',
		categoryBadge: 'K-DIAGNOSTICS',
		objective: 'Evaluate diagnostic metrics across K=2–10 while running a 15-seed K-stability sweep (K=2–7) to validate partition robustness for project-fixed K=4.',
		formulaBadge: 'Stability(K) = mean_pairwise_ARI(KMeans(K, seed_i), KMeans(K, seed_j))',
		latexFormula: '\\overline{\\text{ARI}}(K) = \\frac{2}{S(S - 1)} \\sum_{i=1}^{S-1} \\sum_{j=i+1}^S \\text{ARI}\\Big(\\mathbf{y}_i^{(K)}, \\, \\mathbf{y}_j^{(K)}\\Big) \\quad (S=15)',
		metricBadge: 'K = 4 FIXED (PROJECT SPEC)',
		keyStatLabel: 'Stability Sweep',
		keyStatValue: '15 Seeds / K (K=2..7)',
		techSummary: 'Elbow (inertia), silhouette, and GMM BIC/AIC curves are evaluated across K=2–10 as diagnostic context. K=4 is locked per project requirement. Section 6b introduces a 15-seed ARI sweep across candidate K values (K=2–7) to verify that K=4 produces a stable, reproducible structure compared to neighboring alternatives.',
		bullets: [
			'Diagnostics: Elbow inertia drop, Silhouette score, GMM BIC/AIC evaluated across K=2–10.',
			'K=4 explicitly compared against algorithmic argmax to report true trade-offs transparently.',
			'K-stability sweep across K=2–7 runs 15 seeds per K, reporting mean and std ARI.',
		],
		graphicType: 'k-stability',
		imageSrc: '/assets/spotify/k_stability.png',
	},
	{
		id: 'stage-4',
		stageNumber: 4,
		title: 'Model Selection: KMeans vs GMM',
		subtitle: 'Algorithm Competition at K=4 with Bootstrap Validation (Sec 7)',
		stageTag: 'STAGE 04',
		stageType: 'clustering',
		themeColor: 'var(--geo-black)',
		categoryBadge: 'MODEL SELECTION',
		objective: 'Fit KMeans and GMM (diag covariance) at K=4, select the higher silhouette model, measure inter-model agreement, and validate with 80% bootstrap resampling.',
		formulaBadge: 'KMeans Silhouette = 0.179 vs GMM = 0.165 ∧ Bootstrap ARI = 0.858 ± 0.05',
		latexFormula: '\\text{Winner} = \\operatorname{arg\\,max}\\Big(\\text{Sil}_{\\text{KMeans}}=0.179, \\, \\text{Sil}_{\\text{GMM}}=0.165\\Big)',
		metricBadge: 'KMEANS WINNER (SIL=0.179, DB=1.784)',
		keyStatLabel: 'Bootstrap Stability',
		keyStatValue: 'ARI = 0.858 ± 0.05 (15 Runs)',
		techSummary: 'Rather than assuming KMeans, both algorithms compete at K=4. KMeans achieves silhouette 0.179 and Davies-Bouldin 1.784, outperforming GMM (silhouette 0.165). KMeans vs GMM label agreement has ARI = 0.281. An 80% bootstrap resample across 15 iterations yields ARI = 0.858 ± 0.05, demonstrating high partition resilience.',
		bullets: [
			'KMeans wins with Silhouette = 0.179 and Davies-Bouldin = 1.784.',
			'KMeans vs GMM agreement measured at ARI = 0.281 (captures non-trivial model boundary differences).',
			'15 bootstrap iterations at 80% subsample size confirm strong cluster reproducibility (ARI = 0.858).',
		],
		graphicType: 'gmm',
		imageSrc: '/assets/spotify/cluster_dashboard.png',
	},
	{
		id: 'stage-5',
		stageNumber: 5,
		title: 'Dynamic Z-Score Persona Extraction',
		subtitle: 'Automated Catalog Standardization Naming (Sec 8)',
		stageTag: 'STAGE 05',
		stageType: 'clustering',
		themeColor: 'var(--geo-yellow)',
		categoryBadge: 'PERSONA PROFILING',
		objective: 'Extract descriptive cluster personas dynamically by computing feature z-scores against the full catalog mean, eliminating hardcoded naming.',
		formulaBadge: 'z_{c, f} = (μ_{c, f} - μ_{global, f}) / σ_{global, f} -> Name = Top1 & Top2 Adjectives',
		latexFormula: 'z_{c, f} = \\frac{\\overline{x}_{c, f} - \\mu_f}{\\sigma_f} \\quad \\implies \\quad \\text{Persona}_c = \\text{Adj}(f_1^*) \\ \\& \\ \\text{Adj}(f_2^*)',
		metricBadge: '4 DYNAMIC PERSONAS (169 TRACKS)',
		keyStatLabel: 'Cluster Partition',
		keyStatValue: '4 Vibe Archetypes',
		techSummary: 'Cluster names are derived directly from the two highest absolute z-scores per cluster: Cluster 0 "Acoustic & Mellow" (36 tracks, 21.3%), Cluster 1 "Uplifting & Danceable" (54 tracks, 32.0%), Cluster 2 "Instrumental & Produced" (28 tracks, 16.6%), and Cluster 3 "Bold & Energetic" (51 tracks, 30.2%).',
		bullets: [
			'Automated adjective mapping based on feature deviations (e.g. high acousticness -> "Acoustic", low energy -> "Mellow").',
			'Cluster 0: Acoustic & Mellow (36 tracks, 21.3%).',
			'Cluster 1: Uplifting & Danceable (54 tracks, 32.0%) | Cluster 2: Instrumental & Produced (28 tracks, 16.6%) | Cluster 3: Bold & Energetic (51 tracks, 30.2%).',
		],
		graphicType: 'personas',
	},
	{
		id: 'stage-6',
		stageNumber: 6,
		title: 'Structural Robustness Validation',
		subtitle: 'Feature Sensitivity, 50-Seed Matrix & Per-Track Silhouette (Sec 7b)',
		stageTag: 'STAGE 06',
		stageType: 'validation',
		themeColor: 'var(--geo-black)',
		categoryBadge: 'STRUCTURAL VALIDATION',
		objective: 'Validate whether clustering represents true acoustic geometry or methodological artifacts through feature-set sensitivity, a 50-seed stability matrix, and per-track silhouette distributions.',
		formulaBadge: 's(i) = (b(i) - a(i)) / max(a(i), b(i)) ∧ 50-Seed Pairwise Mean ARI = 0.967',
		latexFormula: 's(i) = \\frac{b(i) - a(i)}{\\max\\big(a(i), \\, b(i)\\big)}, \\quad \\overline{\\text{ARI}}_{\\text{50 seeds}} = 0.967',
		metricBadge: '50-SEED ARI = 0.967 (HIGH ROBUSTNESS)',
		keyStatLabel: 'Diagnostic Tests',
		keyStatValue: '4 Robustness Layers',
		techSummary: 'Section 7b answers "is this clustering real?": 7b.1 tests 6 feature subsets (mean ARI = 0.584), 7b.2 & 7b.3 evaluate 50 random seeds with pairwise mean ARI = 0.967 (visualized via 10x10 heatmap), and 7b.4 plots per-track silhouette distributions to audit borderline negative-score tracks.',
		bullets: [
			'7b.1 Feature-set sensitivity: Evaluates 6 feature variations (all 9, drop correlated, core 5, random 6 x2, PCA 90%).',
			'7b.2 & 7b.3 Seed stability: 50 seeds achieve mean ARI = 0.967, std = 0.048 with a full 10x10 pairwise heatmap.',
			'7b.4 Per-track silhouette: silhouette_samples reveals individual cluster separation and flags borderline tracks.',
		],
		graphicType: 'bootstrap',
		imageSrc: '/assets/spotify/seed_stability_matrix.png',
	},
	{
		id: 'stage-7',
		stageNumber: 7,
		title: 'Manifold Projection & Topology Sensitivity',
		subtitle: 'PCA + UMAP (15-NN) & Neighbor Parameter Sweep (Sec 9 & 9b)',
		stageTag: 'STAGE 07',
		stageType: 'projection',
		themeColor: 'var(--geo-cyan)',
		categoryBadge: 'DIMENSIONALITY REDUCTION',
		objective: 'Project 9D feature space to 3D/2D coordinates via PCA and UMAP (n_neighbors=15, min_dist=0.3) while checking GMM covariance types and UMAP neighbor sensitivity via Spearman distance rank correlation.',
		formulaBadge: 'ρ_Spearman(D_high, D_UMAP) across k ∈ {5, 15, 30, 50}',
		latexFormula: '\\rho = 1 - \\frac{6 \\sum d_i^2}{N(N^2 - 1)}, \\quad \\text{UMAP}(n=15, \\, d_{\\min}=0.3)',
		metricBadge: 'PCA (2 PCs: 54.8%) | UMAP (15-NN)',
		keyStatLabel: 'Coordinate Space',
		keyStatValue: '9D -> 3D Interactive Galaxy',
		techSummary: 'PCA explains 54.8% of variance in the first 2 PCs. UMAP (n_neighbors=15, min_dist=0.3) captures non-linear manifold geometry. Section 9b evaluates GMM covariance assumptions (diag/full/tied/spherical) and tests UMAP neighbor sensitivity (k=5, 15, 30, 50) using Spearman rank correlation of pairwise distances to avoid visual circular reasoning.',
		bullets: [
			'PCA: First 2 principal components capture 54.8% of total catalog variance.',
			'UMAP (n_neighbors=15, min_dist=0.3) maps high-dimensional manifolds to 3D coordinates.',
			'Topology sensitivity: Spearman correlation verifies neighbor stability across k=5, 15, 30, 50.',
		],
		graphicType: 'manifold',
		imageSrc: '/assets/spotify/umap_neighbor_sensitivity.png',
	},
	{
		id: 'stage-8',
		stageNumber: 8,
		title: 'Cosine Recommendations & Web Export',
		subtitle: 'Pairwise Angular Proximity & Unified Web Bundle (Sec 10–13)',
		stageTag: 'STAGE 08',
		stageType: 'similarity',
		themeColor: 'var(--geo-red)',
		categoryBadge: 'EXPORT & APPLICATION',
		objective: 'Compute pairwise cosine similarity across normalized feature vectors for cross-era track recommendations and export a unified web bundle (cluster_summary.json, music_galaxy.json).',
		formulaBadge: 'S_C(u, v) = cos(θ) = (u · v) / (||u||₂ · ||v||₂)',
		latexFormula: 'S_C(\\mathbf{u}, \\mathbf{v}) = \\cos(\\theta) = \\frac{\\sum_{i=1}^9 u_i v_i}{\\sqrt{\\sum_{i=1}^9 u_i^2} \\sqrt{\\sum_{i=1}^9 v_i^2}}',
		metricBadge: '1,000+ PAIRWISE SISTER CONNECTIONS',
		keyStatLabel: 'Export Bundle',
		keyStatValue: 'Unified JSON Web Assets',
		techSummary: 'Pairwise cosine similarity uncovers non-obvious cross-era sister tracks (e.g. 1984 Like a Virgin connecting to 2005 Hung Up). All pipeline outputs are consolidated into clean web artifacts (cluster_summary.json, music_galaxy.json, sonic_recs.json) for the interactive Astro dashboard.',
		bullets: [
			'Cosine metric: Scale-invariant angular distance reveals sonic sister tracks across 4 decades.',
			'Top 5 nearest neighbors exported per track for interactive explorer recommendations.',
			'Single web bundle export (cluster_summary.json + music_galaxy.json) feeds the live Astro visualizer.',
		],
		graphicType: 'wormhole',
	},
] as const;
